version: 2
jobs:
  build: 
    docker:
      - image: circleci/php:7.4.9-node-browsers
      - image: circleci/mysql:5.7-ram
  
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo docker-php-ext-install pdo_mysql
      - run: sudo composer self-update
      - restore_cache:
        keys:
          - composer-v1-{{ checksum "composer.lock" }}
          - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
        key: composer-v1-{{ checksum "composer.lock" }}
        paths:
          - vendor
      - run: vendor/bin/phpunit

